name: Get Citation Data
on: 
  workflow_dispatch:  # 允许手动触发
  page_build: 
  schedule:
    - cron: '0 8 * * *'  # 每天8点运行
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  # 更新到最新版本

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
        pip install -r google_scholar_crawler/requirements.txt

    - name: Run
      run: |
        cd ./google_scholar_crawler
        echo "Start running main.py"
        python3 -v main.py
        cd ./results
        git init
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add *.json
        git commit -m "Updated Citation Data"
        git branch -M main  # 设置分支名为main
        git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git push -f origin main:google-scholar-stats
      env: 
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
        SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
